midi.NOTE_OFF                = 0x80
midi.NOTE_ON                 = 0x90
midi.POLYPHONIC_KEY_PRESSURE = 0xA0
midi.CONTROL_CHANGE          = 0xB0
midi.PROGRAM_CHANGE          = 0xC0
midi.CHANNEL_PRESSURE        = 0xD0
midi.PITCH_BEND_CHANGE       = 0xE0

midi.STATUS_SIZE = {
    [midi.NOTE_OFF]                = 2,
    [midi.NOTE_ON]                 = 2,
    [midi.POLYPHONIC_KEY_PRESSURE] = 2,
    [midi.CONTROL_CHANGE]          = 2,
    [midi.PROGRAM_CHANGE]          = 1,
    [midi.CHANNEL_PRESSURE]        = 1,
    [midi.PITCH_BEND_CHANGE]       = 2
}

midi.STATUS_NAMES = {
    [midi.NOTE_OFF]                = "Note Off",
    [midi.NOTE_ON]                 = "Note On",
    [midi.POLYPHONIC_KEY_PRESSURE] = "Polyphonic Key Pressure",
    [midi.CONTROL_CHANGE]          = "Control Change",
    [midi.PROGRAM_CHANGE]          = "Program Change",
    [midi.CHANNEL_PRESSURE]        = "Channel Pressure",
    [midi.PITCH_BEND_CHANGE]       = "Pitch Bend Change"
}

midi.CC_BANK_SELECT_MSB          = 0
midi.CC_MODULATION_WHEEL         = 1
midi.CC_BREATH_CONTROLLER        = 2
midi.CC_FOOT_PEDAL               = 4
midi.CC_PORTAMENTO_TIME          = 5
midi.CC_DATA_ENTRY_MSB           = 6
midi.CC_VOLUME                   = 7
midi.CC_BALANCE                  = 8
midi.CC_PAN                      = 10
midi.CC_EXPRESSION               = 11
midi.CC_EFFECT_CONTROLLER_1      = 12
midi.CC_EFFECT_CONTROLLER_2      = 13
midi.CC_GENERAL_PURPOSE_16       = 16
midi.CC_GENERAL_PURPOSE_17       = 17
midi.CC_GENERAL_PURPOSE_18       = 18
midi.CC_GENERAL_PURPOSE_19       = 19
midi.CC_DAMPER_PEDAL             = 64
midi.CC_PORTAMENTO_ON_OFF        = 65
midi.CC_SOSTENUTO_PEDAL          = 66
midi.CC_SOFT_PEDAL               = 67
midi.CC_LEGATO_FOOTSWITCH        = 68
midi.CC_HOLD_2                   = 69
midi.CC_SOUND_CONTROLLER_1       = 70
midi.CC_SOUND_CONTROLLER_2       = 71
midi.CC_SOUND_CONTROLLER_3       = 72
midi.CC_SOUND_CONTROLLER_4       = 73
midi.CC_SOUND_CONTROLLER_5       = 74
midi.CC_SOUND_CONTROLLER_6       = 75
midi.CC_SOUND_CONTROLLER_7       = 76
midi.CC_SOUND_CONTROLLER_8       = 77
midi.CC_SOUND_CONTROLLER_9       = 78
midi.CC_SOUND_CONTROLLER_10      = 79
midi.CC_GENERAL_PURPOSE_80       = 80
midi.CC_GENERAL_PURPOSE_81       = 81
midi.CC_GENERAL_PURPOSE_82       = 82
midi.CC_GENERAL_PURPOSE_83       = 83
midi.CC_PORTAMENTO_CONTROL       = 84
midi.CC_HIGH_RES_VELOCITY_PREFIX = 88
midi.CC_EFFECT_1_DEPTH           = 91
midi.CC_EFFECT_2_DEPTH           = 92
midi.CC_EFFECT_3_DEPTH           = 93
midi.CC_EFFECT_4_DEPTH           = 94
midi.CC_EFFECT_5_DEPTH           = 95
midi.CC_DATA_INCREMENT           = 96
midi.CC_DATA_DECREMENT           = 97
midi.CC_NRPN_LSB                 = 98
midi.CC_NRPN_MSB                 = 99
midi.CC_RPN_LSB                  = 100
midi.CC_RPN_MSB                  = 101
midi.CC_ALL_SOUND_OFF            = 120
midi.CC_RESET_ALL_CONTROLLERS    = 121
midi.CC_LOCAL_ON_OFF             = 122
midi.CC_ALL_NOTES_OFF            = 123
midi.CC_OMNI_MODE_OFF            = 124
midi.CC_OMNI_MODE_ON             = 125
midi.CC_MONO_MODE                = 126
midi.CC_POLY_MODE                = 127

midi.CC_NAMES = {
    [midi.CC_BANK_SELECT_MSB]          = "Bank Select (MSB)",
    [midi.CC_MODULATION_WHEEL]         = "Modulation Wheel",
    [midi.CC_BREATH_CONTROLLER]        = "Breath Controller",
    [midi.CC_FOOT_PEDAL]               = "Foot Pedal",
    [midi.CC_PORTAMENTO_TIME]          = "Portamento Time",
    [midi.CC_DATA_ENTRY_MSB]           = "Data Entry (MSB)",
    [midi.CC_VOLUME]                   = "Volume",
    [midi.CC_BALANCE]                  = "Balance",
    [midi.CC_PAN]                      = "Pan",
    [midi.CC_EXPRESSION]               = "Expression",
    [midi.CC_EFFECT_CONTROLLER_1]      = "Effect Controller 1",
    [midi.CC_EFFECT_CONTROLLER_2]      = "Effect Controller 2",
    [midi.CC_GENERAL_PURPOSE_16]       = "General Purpose 16",
    [midi.CC_GENERAL_PURPOSE_17]       = "General Purpose 17",
    [midi.CC_GENERAL_PURPOSE_18]       = "General Purpose 18",
    [midi.CC_GENERAL_PURPOSE_19]       = "General Purpose 19",
    [midi.CC_DAMPER_PEDAL]             = "Damper Pedal (Sustain)",
    [midi.CC_PORTAMENTO_ON_OFF]        = "Portamento On/Off",
    [midi.CC_SOSTENUTO_PEDAL]          = "Sostenuto Pedal",
    [midi.CC_SOFT_PEDAL]               = "Soft Pedal",
    [midi.CC_LEGATO_FOOTSWITCH]        = "Legato Footswitch",
    [midi.CC_HOLD_2]                   = "Hold 2",
    [midi.CC_SOUND_CONTROLLER_1]       = "Sound Controller 1",
    [midi.CC_SOUND_CONTROLLER_2]       = "Sound Controller 2",
    [midi.CC_SOUND_CONTROLLER_3]       = "Sound Controller 3",
    [midi.CC_SOUND_CONTROLLER_4]       = "Sound Controller 4",
    [midi.CC_SOUND_CONTROLLER_5]       = "Sound Controller 5",
    [midi.CC_SOUND_CONTROLLER_6]       = "Sound Controller 6",
    [midi.CC_SOUND_CONTROLLER_7]       = "Sound Controller 7",
    [midi.CC_SOUND_CONTROLLER_8]       = "Sound Controller 8",
    [midi.CC_SOUND_CONTROLLER_9]       = "Sound Controller 9",
    [midi.CC_SOUND_CONTROLLER_10]      = "Sound Controller 10",
    [midi.CC_GENERAL_PURPOSE_80]       = "General Purpose 80",
    [midi.CC_GENERAL_PURPOSE_81]       = "General Purpose 81",
    [midi.CC_GENERAL_PURPOSE_82]       = "General Purpose 82",
    [midi.CC_GENERAL_PURPOSE_83]       = "General Purpose 83",
    [midi.CC_PORTAMENTO_CONTROL]       = "Portamento Control",
    [midi.CC_HIGH_RES_VELOCITY_PREFIX] = "High Resolution Velocity Prefix",
    [midi.CC_EFFECT_1_DEPTH]           = "Effect 1 Depth",
    [midi.CC_EFFECT_2_DEPTH]           = "Effect 2 Depth",
    [midi.CC_EFFECT_3_DEPTH]           = "Effect 3 Depth",
    [midi.CC_EFFECT_4_DEPTH]           = "Effect 4 Depth",
    [midi.CC_EFFECT_5_DEPTH]           = "Effect 5 Depth",
    [midi.CC_DATA_INCREMENT]           = "Data Increment",
    [midi.CC_DATA_DECREMENT]           = "Data Decrement",
    [midi.CC_NRPN_LSB]                 = "NRPN LSB",
    [midi.CC_NRPN_MSB]                 = "NRPN MSB",
    [midi.CC_RPN_LSB]                  = "RPN LSB",
    [midi.CC_RPN_MSB]                  = "RPN MSB",
    [midi.CC_ALL_SOUND_OFF]            = "All Sound Off",
    [midi.CC_RESET_ALL_CONTROLLERS]    = "Reset All Controllers",
    [midi.CC_LOCAL_ON_OFF]             = "Local On/Off",
    [midi.CC_ALL_NOTES_OFF]            = "All Notes Off",
    [midi.CC_OMNI_MODE_OFF]            = "Omni Mode Off",
    [midi.CC_OMNI_MODE_ON]             = "Omni Mode On",
    [midi.CC_MONO_MODE]                = "Mono Mode",
    [midi.CC_POLY_MODE]                = "Poly Mode"
}

midi.INSTRUMENT_NAMES = {
    [1] = "Acoustic Grand Piano",
    [2] = "Bright Acoustic Piano",
    [3] = "Electric Grand Piano",
    [4] = "Honky-tonk Piano",
    [5] = "Electric Piano 1",
    [6] = "Electric Piano 2",
    [7] = "Harpsichord",
    [8] = "Clavinet",
    [9] = "Celesta",
    [10] = "Glockenspiel",
    [11] = "Music Box",
    [12] = "Vibraphone",
    [13] = "Marimba",
    [14] = "Xylophone",
    [15] = "Tubular Bells",
    [16] = "Dulcimer",
    [17] = "Drawbar Organ",
    [18] = "Percussive Organ",
    [19] = "Rock Organ",
    [20] = "Church Organ",
    [21] = "Reed Organ",
    [22] = "Accordion",
    [23] = "Harmonica",
    [24] = "Tango Accordion",
    [25] = "Acoustic Guitar (nylon)",
    [26] = "Acoustic Guitar (steel)",
    [27] = "Electric Guitar (jazz)",
    [28] = "Electric Guitar (clean)",
    [29] = "Electric Guitar (muted)",
    [30] = "Overdriven Guitar",
    [31] = "Distortion Guitar",
    [32] = "Guitar harmonics",
    [33] = "Acoustic Bass",
    [34] = "Electric Bass (finger)",
    [35] = "Electric Bass (pick)",
    [36] = "Fretless Bass",
    [37] = "Slap Bass 1",
    [38] = "Slap Bass 2",
    [39] = "Synth Bass 1",
    [40] = "Synth Bass 2",
    [41] = "Violin",
    [42] = "Viola",
    [43] = "Cello",
    [44] = "Contrabass",
    [45] = "Tremolo Strings",
    [46] = "Pizzicato Strings",
    [47] = "Orchestral Harp",
    [48] = "Timpani",
    [49] = "String Ensemble 1",
    [50] = "String Ensemble 2",
    [51] = "Synth Strings 1",
    [52] = "Synth Strings 2",
    [53] = "Choir Aahs",
    [54] = "Voice Oohs",
    [55] = "Synth Voice",
    [56] = "Orchestra Hit",
    [57] = "Trumpet",
    [58] = "Trombone",
    [59] = "Tuba",
    [60] = "Muted Trumpet",
    [61] = "French Horn",
    [62] = "Brass Section",
    [63] = "Synth Brass 1",
    [64] = "Synth Brass 2",
    [65] = "Soprano Sax",
    [66] = "Alto Sax",
    [67] = "Tenor Sax",
    [68] = "Baritone Sax",
    [69] = "Oboe",
    [70] = "English Horn",
    [71] = "Bassoon",
    [72] = "Clarinet",
    [73] = "Piccolo",
    [74] = "Flute",
    [75] = "Recorder",
    [76] = "Pan Flute",
    [77] = "Blown Bottle",
    [78] = "Shakuhachi",
    [79] = "Whistle",
    [80] = "Ocarina",
    [81] = "Lead 1 (square)",
    [82] = "Lead 2 (sawtooth)",
    [83] = "Lead 3 (calliope)",
    [84] = "Lead 4 (chiff)",
    [85] = "Lead 5 (charang)",
    [86] = "Lead 6 (voice)",
    [87] = "Lead 7 (fifths)",
    [88] = "Lead 8 (bass + lead)",
    [89] = "Pad 1 (new age)",
    [90] = "Pad 2 (warm)",
    [91] = "Pad 3 (polysynth)",
    [92] = "Pad 4 (choir)",
    [93] = "Pad 5 (bowed)",
    [94] = "Pad 6 (metallic)",
    [95] = "Pad 7 (halo)",
    [96] = "Pad 8 (sweep)",
    [97] = "FX 1 (rain)",
    [98] = "FX 2 (soundtrack)",
    [99] = "FX 3 (crystal)",
    [100] = "FX 4 (atmosphere)",
    [101] = "FX 5 (brightness)",
    [102] = "FX 6 (goblins)",
    [103] = "FX 7 (echoes)",
    [104] = "FX 8 (sci-fi)",
    [105] = "Sitar",
    [106] = "Banjo",
    [107] = "Shamisen",
    [108] = "Koto",
    [109] = "Kalimba",
    [110] = "Bag pipe",
    [111] = "Fiddle",
    [112] = "Shanai",
    [113] = "Tinkle Bell",
    [114] = "Agogo",
    [115] = "Steel Drums",
    [116] = "Woodblock",
    [117] = "Taiko Drum",
    [118] = "Melodic Tom",
    [119] = "Synth Drum",
    [120] = "Reverse Cymbal",
    [121] = "Guitar Fret Noise",
    [122] = "Breath Noise",
    [123] = "Seashore",
    [124] = "Bird Tweet",
    [125] = "Telephone Ring",
    [126] = "Helicopter",
    [127] = "Applause",
    [128] = "Gunshot",
}

midi.NOTE_NAMES = {
    "C",
    "C#",
    "D",
    "D#",
    "E",
    "F",
    "F#",
    "G",
    "G#",
    "A",
    "A#",
    "B"
}